name: AchalHello

on:
  push:
    branches: [ "Achal" ]
  pull_request:
    branches: [ "Achal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello Achal! Looking great as always"
